

--16----23


/*16. LEFT ou RIGHT ou FULL OUTER JOIN
17. SUBCONSULTA COM OPERADOR RELACIONAL
18. SUBCONSULTA COM IN
19. SUBCONSULTA COM ANY
20. SUBCONSULTA COM ALL
21. ORDER BY
22. GROUP BY---------------------------
23. HAVING
*/


--- NUMEOR DE VENDA DOS FUNCIONARIOS  agrupando por homem e MULHERES
SELECT  P.genero, SUM(F.num_alugueis)  
from Pessoa P
JOIN Funcionario F ON P.cpf=F.cpf_f
GROUP BY P.genero

----mandar email pros cliente que moram longe perto da locadoa, avisadno de um evento ----join e in no endere;o perto da livraira

SELECT E.email
FROM Email E
JOIN PESSOA P ON E.cpf_e=P.cpf
WHERE P.






---- contar quantos produtos tiverem avaliacao maior que 

---group by rodutos havinf avaliacao maior que 7








--------------------
SELECT PV.NOTA FROM PESSOA P
JOIN ALUNO A 
    ON P.MATRICULA_PESSOA==A.MATRICULA_ALUNO
JOIN PROVA PV 
    ONWHERE P.NOM="Augustus Kilter" and PV.aluno_semestre='2016.2'



SELECT P.TITULO, AT.ANO_SEMESTRE,P.CONCEITO
FROM PESSOA P
INNER JOIN ALUNO A ON P.MATRICULA=A.MATRICULA_ALUNO
INNER JOIN ALUNO_TURMA AT ON A.MATRICULA_ALUNO=AT.MATRICULA_ALUNO
INNER JOIN PROJETO PR ON AT.CODIGO_PROJETO=PR.CODIGO_PROJETO
WHERE P.NOME='JOAO CUSTODIA'
ORDER BY AT.ANO_SEMESTRE, PR.CONCEITO


SELECT PROF.matriculka_professor, P1.nome , AT. CODIGO_DICIPLINA --P1-PESSOA PROFESSOR
FROM PESSOA P1
INNER JOIN MINISTRA M ON P1.matricula_pROFESSOR= M.MATRICULA_MATRICULA_PROFESSOR
INNER JOIN ALUNO_TURMA AT ON M.CODIGO_DICIPLINA=AT.CODIGO_DICIPLINA
    AND M.ANO_SEMESTRE=AT.ANO_SEMESTRE
    AND M.CODIGO_CURSO=AT.CODIGO_CURSO
INNER JOIN PESSOA P2 ON AT.MATRICULA_ALUNO =P2.MATRICULA_PESSOA
WHERE P2.NOME='HELENA NUNES' AND AT.ANO_SEMESTRE=(SELECT MIN(AT2.ANO_SEMESTRE)
                                                FROM ALUNO A
                                                JOIN ALUNO_TURMA AT2 ON A.MATRICULA_ALUNO=AT2.ALUNO_MATRICULA
                                                WHERE  A.MATRICULA= P2.MATRICULA_PESSOA)



SELECT PROJ.TITULO, AT.ANO_SEMESTRE, C.NOME, P.NOME
FROM PESSOA P 
INNER JOIN ALUNO_TURMA AT 
    ON P.MATRICULA_PESSOA=AT.MATRICULA_ALUNO
LEFT JOIN PROJETO PROJ
    ON AT.CODIGO_PROJETO=PROJ.CODIGO_PROJETO
INNER JOIN CURSO C
    ON AT.CODIGO_CURSO=C.CODIGO_CURSO
WHERE AT.CODIGO_DICIPLINA='5' 


SELECT P1.NOME AS LIDERADO, P2.NOME AS LIDER
FROM PROFESSOR PR1
    FULL JOIN PROFESSOR PR2 ON PR1.MATRICULA_LIDER=PR2.matricula_pROFESSOR
    LEFT JOIN PESSOA P1 ON P1.MATRICULA_PESSOA=PR1.MATRICULA_PROFESSOR
    LEFT JOIN PESSOA P2 ON P2.MATRICULA_PESSOA=PR2.MATRICULA_PROFESSOR